export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUT_SUCCESS'
export const CREATE_ACCOUT_FAILURE = 'CREATE_ACCOUT_FAILURE'
export const RESET_CREATE_ACCOUNT = 'RESET_CREATE_ACCOUNT'
